name: first workflow
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "Hello first workflow"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: hello second job
        run: echo "Hello second job"
  reuse-job:
    needs: [first-job, second-job]
    uses: ./.github/workflows/reuse-task.yaml