name: first workflow
on: push
jobs:
  first-job:
    if: github.ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "Hello first workflow"

      - name: Reuse Task
        uses: ./.github/workflows/reuse-task.yaml